name: tasky
description: "Task Management & To-Do List"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.3
  flutter_bloc: ^8.1.6

  dio: ^5.7.0
  http: ^1.2.2
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  phone_form_field: ^10.0.2
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  pretty_qr_code: ^3.3.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.6
  image: ^4.5.0
  mobile_scanner: ^6.0.2
  mime: ^2.0.0
  http_parser: ^4.1.1
  pretty_dio_logger: ^1.4.0

dependency_overrides:
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700



flutter_native_splash:

  color: "#5F33E1"
  image: assets/images/logo.png

  android_12:
    image: assets/images/splash_android12_logo.png
    color: "#5F33E1"